spring:
  application:
    name: rodinneDomy

  datasource:
    url: jdbc:postgresql://localhost:5555/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver